### ISSUE TITLE
Crashes on pairing to bridge

### ISSUE THREAD

**Issue by Phnyxen** [Hyrules/WinHue#262]
WinHue version : 3.0.4773.0)
Bridge model: BSB002, Version: 1935074050 
I have installed Winhue on another pc with same bridge without problems.
On this one I get an error when trying to link to bridge. 
Winhue finds the bridge, and crashes when I press "Pair".
I include the crash log.
[WinHue3.log](https://github.com/Hyrules/WinHue/files/3774684/WinHue3.log)

**Comment by Hyrules** [comment]
Seems the app is unable to get the ApiVersion from the bridge when trying to find it.  I would need this in order to find why the program is crashing.

Paste this in your favorite browser : http://192.168.0.17/api/FkkFiQO3grQI4clQC83yxsJUGwvjKVh0Ie89OMAk/config

you will see apiversion somewhere. i need this value to see if which bridge apiversion you have.

**Comment by Phnyxen** [comment]
Hi, Hyrules
Thank you for responding.
The bridge has the ip: 192.168.0.32, not .17 - that is a previous bridge.
Anyway I get:
"apiversion":"1.35.0"

**Comment by Hyrules** [comment]
Yeah but is there a bridge at IP: 192.168.0.17 ? If so this might be the cause of the crash if the api is too old and not returning the version.

**Comment by Phnyxen** [comment]
I only have one bridge - I guess the 17 is the old one - which is no longer connected.

**Comment by Hyrules** [comment]
go into %APPDATA%\WinHue in windows explorer and try deleting the WinHueBridges.set and pair your bridge again. Let me know what happens.

**Comment by Phnyxen** [comment]
Huii! Success! Had to delete appdata a couple of places. 
Thank you very much for your help.

**Comment by Hyrules** [comment]
go to know it is fixed.
